### ISSUE TITLE
BioSequences.jl 0.6

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/BioSequences.jl#10]
I'd like to release a new version of BioSequences.jl because:
- It started to support Julia 0.6.
- I cannot finish Julia 0.6 support of GenomicFeatures.jl since it depends on BioSequences.jl 0.5, which depends on PairwiseListMatrices.jl, which doesn't support Julia 0.6.
- We added a new feature (#7) and a bug fix (#8).

**Comment by Ward9250** [comment]
Let's do it!

**Comment by bicycle1885** [comment]
Thank you for releasing it 💯

**Comment by Ward9250** [comment]
I've looked over the repo and I haven't seen anything furthur to do, so I've gone and tagged the release, if there's any changes to be made we've a 24 hour window with METADATA.jl and we can just change it.
