### ISSUE TITLE
Streamline find functions to behave like Base's

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/BioSequences.jl#141]
Right now, you can do:
```
julia> findfirst(DNA_A, dna"TAGCGATGA")
2
```
Whereas it should be:
```
julia> findfirst(isequal(DNA_A), dna"TAGCGATGA")
2
```
The latter example currently errors. This happens because the predicate version of find* in BioSequences are currently restricted to subtypes of Function. But there are many function-like objects (such as e.g. Base.Fix2), which are not instances of Function.

We should remove `findfirst(DNA_A, dna"TAG")`, and make sure these functions behave as expected.

**Comment by kescobo** [comment]
A counterpoint - it depend on whether we think of `BioSequence`s more like strings, or more like generic iterables, since:

```
julia> findfirst('a', "garden")
2

julia> findfirst(3, 1:5)
ERROR: MethodError: no method matching findfirst(::Int64, ::UnitRange{Int64})
# ...

julia> findfirst("ard", "garden")
2:4
```

I think it might make sense to keep this out of the next major release, and then we can always add it back later without it being a breaking change

**Comment by jakobnissen** [comment]
Another option, perhaps a better compromise:
Currently `findfirst(dna"A", dna"TNG")` and `findfirst(DNA_A, dna"TNG")` behave differently. The former will report the `N` as being an `A`, because they are compatible, the latter will not.

Perhaps we can remove that consistency by instead having them both behave in the former manner? For exact sequence comparison, one can then use `findfirst(isequal(DNA_A), dna"TNG")`.

I would still like to restrict the latter to only be able to search for instances of `BioSymbol`.

**Comment by kescobo** [comment]
Oh, that's interesting. I don't have a good sense of what makes sense as an API. 

Are you saying that you do not want to allow searches akin to `findfirst("ard", "garden")`? Given the complexity of sequence comparison in biology, I think that's perfectly justifiable. I can imagine a function that takes a scoring matrix and finds the first match, but then it's not really `findfirst` anymore.

**Comment by jakobnissen** [comment]
No, in the merged fork where I deleted the regular findfirst, you can still do `findfirst("ard", "garden")`, and it does this specific search where it searches for the first compatible subsequence given ambiguous nucleotides.

It's the strange situation with searching for single symbols in sequences I want to change. Either:
* Remove `findfirst('a', "garden")` and only rely on `findfirst(isequal('a'), "garden")`, or
* Let the former search for compatible subsequences, just like `findfirst("ard", "garden")` already does, and let the latter be used for exact search (like in Base).

**Comment by kescobo** [comment]
Ahh. I personally like option 2 best.

**Comment by jakobnissen** [comment]
Let's do that.

**Comment by CiaranOMara** [comment]
I think the default search should be the `isequal` as it provides the least unexpected result and is probably what beginners would expect. As an aside, when I first used `BioSequences`, the `ExactSearchQuery` tripped me as I did not expect it to match an explicit pattern to ambiguous symbols within a sequence. I think our other search types should be wrapped by an `AbstractBioSequencesSearchQuery` type such that we can have `findfirst(predicate::AbstractBioSequencesSearchQuery, seq::BioSequence)` and move towards implementing iterators. This approach may get us around that `Base.Fix2` thing -- what do other people think?

I wasn't able to follow peoples expectations regarding character and string like queries. Have I got the following correct?
- `findfirst('a', "garden")` is analogous to `findfirst(DNA_A, dna"GATC")` such that the result is `2`.
- `findfirst("a", "garden")` is analogous to `findfirst(dna"a", dna"GATC")` such that the result is `2:2`.

**Comment by jakobnissen** [comment]
Yeah, I'd like this before v3. I'm pretty busy this week (and perhaps next), but after that I can spend some time wrapping up all the v3 stuff.

Maybe we should have a keyword, say `exact` which currently defaults to `false`.
I'm planning on doing:
* `findfirst(::BioSequence, ::BioSequence, false)` -> Returns nothing or range of first match, considering ambiguity
* `findfirst(::BioSequence, ::BioSequence, true)` -> Returns nothing or range of first match, must be exact match
* `findfirst(isequal(x), ::BioSequence)` -> Nothing or first match of symbol, must be exact
* `findfirst(iscompatible(x), ::BioSequence)` -> Nothing or first match of symbol, considers ambiguity

I think this is the least surprising:
* It uses only one function name instead of having multiple very similar functions
* The two latter ones behave exactly as Base would have you expect
* For the two former, it's a little annoying adding an optional argument to a Base function, but it should be OK, an optional argument is pretty discoverable.

As for whether it should default to considering ambiguous matches or not... hmm, I'm _ambiguous_. I would lean towards keeping the current behaviour, just out of inertia, but I also realize it can be a gotcha. The issue is that I think it can be a gotcha either way.
