### ISSUE TITLE
ERROR: UndefVarError: FASTA not defined

### ISSUE THREAD

**Issue by nurmians** [BioJulia/BioSequences.jl#152]
julia> fst::BioSequences.FASTA.Reader
ERROR: UndefVarError: FASTA not defined

Ok... who broke this? I'm going back to Python, can't deal with this mess.

> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Package Version used:
- Julia Version used:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by jakobnissen** [comment]
Dear @nurmians 

Nothing is broken here. FASTA/FASTQ writers were [removed from BioSequences for v2](https://github.com/BioJulia/BioSequences.jl/blob/master/CHANGELOG.md#20). To get FASTA functionality, install the package `FASTX`.
