### ISSUE TITLE
Implement reverse translation (AminoAcid -> Codon)

### ISSUE THREAD

**Issue by BeastyBlacksmith** [BioJulia/BioSequences.jl#168]
I am thinking about where a good place for the [codon and aminoacid tables](https://en.wikipedia.org/wiki/DNA_and_RNA_codon_tables) would be in julia and wanted to ask if it would fit in here.
## Expected Behavior
```julia
convert(Vector{RNAMer{3}}, AA_A) == RNAMer{3}.(["GCU", "GCA", "GCC", "GCG"])
convert(AminoAcid, RNAMer{3}("GCU")) == AA_A 
```
Maybe have an extra type alias `const Codon = RNAMer{3}`

## Possible Solution / Implementation
Add two lookup tables.

## Context
Could go alternatively in a separate package.

**Comment by jakobnissen** [comment]
All of this is already implemented in BioSequences.jl:

```
julia> using BioSequences

julia> DNACodon
Mer{DNAAlphabet{2}, 3}

julia> RNACodon
Mer{RNAAlphabet{2}, 3}
```

See also https://biojulia.net/BioSequences.jl/stable/transforms/#Translation-1

**Comment by jakobnissen** [comment]
Closing as resolved - if there are any features you'd want to add, you are free to comment and I'll re-open

**Comment by BeastyBlacksmith** [comment]
Indeed this works in the Codon -> AminoAcid direction, but not in the reverse direction.
Furthermore I'd like to do this with single codons without having to convert them to `LongRNASeq`

**Comment by jakobnissen** [comment]
Translation of single DNA codons is a feature in the upcoming v3, already implemented. There is no such thing as reverse translation in `BioSequences`. We could add that

**Comment by jakobnissen** [comment]
I added an implementation here https://github.com/jakobnissen/play/blob/master/revtrans.jl (also see [the accompanying blog post](https://viralinstruction.com/posts/codonset/).

The plan now is to wait for BioSequences v3 where kmers are moved to another repo, and then implement reverse translation in that repo.

**Comment by jakobnissen** [comment]
This issue is now tracked here: https://github.com/BioJulia/Kmers.jl/issues/9
