### ISSUE TITLE
No version for Julia 1.6.1

### ISSUE THREAD

**Issue by ammonite** [BioJulia/BioSequences.jl#185]
> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Package Version used:
- Julia Version used:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by jakobnissen** [comment]
BioSequences work with Julia 1.6.1. It looks like your General registry is corrupted. Try deleting the registry and re-installing it:
```julia
pkg> registry rm General
pkg> registry add General
```

**Comment by ammonite** [comment]
Thank you very much @jakobnissen, BioSequencs work with 1.6.1
