### ISSUE TITLE
No version for Julia 1.6.1

### ISSUE THREAD

**Issue by ammonite** [BioJulia/BioSequences.jl#186]
add BioSequences get ERROR:
ERROR: Unsatisfiable requirements detected for package BioSequences [7e6ae17a]:
 BioSequences [7e6ae17a] log:
 ├─BioSequences [7e6ae17a] has no known versions!
 └─restricted to versions * by an explicit requirement — no versions left

**Comment by jakobnissen** [comment]
Closing as duplicate of #185
