### ISSUE TITLE
LongDNA, LongRNA "not defined"

### ISSUE THREAD

**Issue by fpmenninger** [BioJulia/BioSequences.jl#216]
> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Expected Behavior

julia> LongDNA{2}("TTAGC")
5nt DNA Sequence:
TTAGC

julia> LongRNA{2}("UUAGC")
5nt RNA Sequence:
UUAGC

## Current Behavior

julia> LongDNA{2}("TTAGC")
ERROR: UndefVarError: LongDNA not defined
Stacktrace:
 [1] top-level scope
   @ REPL[20]:1

julia> LongRNA{2}("UUAGC")
ERROR: UndefVarError: LongRNA not defined
Stacktrace:
 [1] top-level scope
   @ REPL[21]:1

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Package Version used:
- Julia Version used: 1.7.1
- Operating System and version (desktop or mobile): Windows 10
- Link to your project:

**Comment by SabrinaJaye** [comment]
I'm not able to replicate this behaviour for julia 1.6 and BioSequences v3.

```julia
             _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.2 (2021-07-14)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

(@v1.6) pkg> add BioSequences
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [7e6ae17a] + BioSequences v3.0.0
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [7e6ae17a] + BioSequences v3.0.0
  [3c28c6f8] + BioSymbols v5.1.0
  [7200193e] + Twiddle v1.1.2

julia> using BioSequences

julia> LongDNA{2}("ATCG")
4nt DNA Sequence:
ATCG

julia> LongRNA{2}("AUCG")
4nt RNA Sequence:
AUCG

```

**Comment by SabrinaJaye** [comment]
Can you do a `Pkg.status()` to see which version of BioSequences you are on?

**Comment by fpmenninger** [comment]
after a package update...

(@v1.7) pkg> status
  [7e6ae17a] BioSequences v2.0.5

**Comment by SabrinaJaye** [comment]
Ok so `LongDNA` and `LongRNA` are the type aliases used in v3 of BioSequences onwards, so you'll need to do

`(@v1.7) pkg> up` to make sure it's set to v3.

**Comment by fpmenninger** [comment]
Thank you for the help.
I see the issue isn't with BioSequences.
Instead, I have to figure out why the package won't upgrade...
Ah. Found (and deleted) a folder in .julia/registries: BioJuliaRegistry
which had a readme stating
The BioJulia Registry has been depreceated and merged into the JuliaRegistries/General registry.
