### ISSUE TITLE
🐛 in iscanonical / canonical

### ISSUE THREAD

**Issue by SabrinaJaye** [BioJulia/BioSequences.jl#225]
Consider these two codons, both RC of each other:

```
a = dna"TCA"
b = dna"TGA"
```

The first one is the canonical, as a < b, as `DNA_C < DNA_G`

However,

```
julia> iscanonical(dna"TCA")
true

julia> iscanonical(dna"TGA")
true
```

And so, `canonical` will return the input sequence for both of these.

**Comment by jakobnissen** [comment]
TGA is definitely not canonical so that is clearly a bug
