### ISSUE TITLE
`Base.eltype(::Type{<:Alphabet})` violates `eltype` docstring

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/BioSequences.jl#231]
It states it gives the type of elements generated when iterating over the collection. But alphabets are not iterable.
Not sure how to fix this. I certainly don't want to break the shiny new interface of BioSequences. Maybe just add `Base.iterate(x::Alphabet, state...) = iterate(symbols(x), state...)`?

**Comment by CiaranOMara** [comment]
I think the idea of an `Alphabet` being a set is correct and offers some useful constructs. For example, It would be nice to be able to do `issubset(symbols, alphabet)`.
