### ISSUE TITLE
domain name of this repo should be updated

### ISSUE THREAD

**Issue by ctarn** [BioJulia/BioSequences.jl#276]
current url `http://biojulia.net/BioSequences.jl` has been redirected to an unrelated website

**Comment by ctarn** [comment]
similar issues also exist in other repos

**Comment by kescobo** [comment]
Do you mean here?

![image](https://github.com/BioJulia/BioSequences.jl/assets/3502975/d18edcd7-5640-4271-beba-960701d438af)

Just fixed this one, and thanks for pointing it out! We lost the `.net` domain a few months ago and I updated it in the READMEs, but didn't think about the repo descriptions. Do you recall where else you saw it?

**Comment by kescobo** [comment]
Never mind, I see it's everywhere :frowning_face: 

I'll go through and try to get them all - please do let us know if you see more of those `.net` links in the wild, and apologies for the irritation

**Comment by ctarn** [comment]
Yes, that's what I meant. Thanks for your efforts. 😁
