### ISSUE TITLE
Get this package back into PkgEval

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/BioSequences.jl#295]
I've found that BioSequences.jl recently got blacklisted from Julia's PkgEval runs. This means the Julia devs will not get notified if a Julia change breaks BioSequences.
I'm looking into what caused this issue and if it can be reverted. My hypothesis now is that the CI check that I disabled in #291 would randomly fail BioSequences so often in PkgEval runs that the package got flagged as unstable, and thus got blacklisted.
If that's the case, then we should remove this CI check from every functional BioJulia package before they get blacklisted, too.

**Comment by jakobnissen** [comment]
Ah, no the reason was something else, see the commit message of 2f9ff46. I should have just cut a new release.

**Comment by jakobnissen** [comment]
Tim Besard cleared it up for me:
* BioSequences is not blacklisted, but put on the skip list. This indeed happens when it fails too often.
* Skipped packages are still evaluated in a daily run
* When these packages begin to work again, they are automatically removed from the skip list.
So, false alarm. No problems after all :)

**Comment by kescobo** [comment]
Thanks for looking into that!
