### ISSUE TITLE
We need a codon type for work with coding sequences.

### ISSUE THREAD

**Issue by Ward9250** [BioJulia/BioSequences.jl#3]
We need a codon type for working with sequences that code for proteins.

Currently translation of proteins is done by iterating over 3-mers with a step size of 3.
The Kmer types almost work for this purpose - catching ambiguous characters.
However, they fall short when it comes to Gaps.
See if you try to make a Kmer with gaps you don't get what you might expect:

```julia
julia> kmer"AAA"
DNA 3-mer:
AAA

julia> kmer"AA-"
DNA 3-mer:
AGA

julia> kmer"---"
DNA 3-mer:
GGA
```
So for codons containing gaps e.g. "AA-", you want to throw error.
Even more complex, if you're dealing with sequences aligned by codons, then if you have a site:

"""
.....ACG......
.....- - -......
"""

Then you may want a codon to be able to represent "---", three gaps is a valid site you might want to work with in that context.

In addition, using 64 bits to store just three nucleotide characters is wasteful - a byte will do it.

I propose a new bitstype called `Codon`, based somewhat on Kmers, but that have a separate representation and that catch and account for gaps.

Such a type will pave the way to having higher level abstractions of sequences with reading frames for example, and gene models. But for now, such a type will allow me to add utilities for looking at signals of selection in sequences.

**Comment by bicycle1885** [comment]
I think kmer literals including gaps like `kmer"AC-"` should throw an error; kmers are originally unambiguous and non-gapped short sequences that fit in an integer. Also, translating codons with gaps doesn't make sense to me. So, it should result in an error.

**Comment by Ward9250** [comment]
Actually being able to represent a codon of "---" should not be an error as a "AC-" is. Yes you can't translate a "---" "codon", but any time you are dealing with sequences aligned by codon, then suddenly when iterating over codons, perfectly valid sites of say "ACG" and "---", where an entire codon is subject to indel throws errors, when you actually want to them and want to deal with them.

**Comment by Ward9250** [comment]
@bicycle1885 Consider for example biopython:

```python
>>> p = CodonSeq('AAA------------TAA', rf_table=(0, 3))
>>> p
CodonSeq('AAA------------TAA', CodonAlphabet(Standard))
>>> p.translate()
'K*'
>>> p.full_translate()
'K----*'
>>> p.get_codon(2)
'---'

# So gaps in a codon aligned sequence, cause frame shift, meaning a codon should not ever contain gaps (as indicated by p.translate() output), BUT when dealing with aligned sequences, you need to be able to represent '---' (in DNA, which == '-' in AA), as indicated by the output of `p.full_translate`, and `p.get_codon`.  
```

Our Kmer types disallow

**Comment by Ward9250** [comment]
We don't need this now.
