### ISSUE TITLE
PFM just accepts vectors?

### ISSUE THREAD

**Issue by felipe-mansoldo** [BioJulia/BioSequences.jl#310]
Hi,

I am testing the PWM and PFM function. But when I tested just one DNA sequence I had problems, but 1 sequence within a vector does not present an error.
See:

```
dna1 = dna"TCA"
pfm = PFM(dna1)
```

```
ArgumentError: sequence element must be DNA or RNA

Stacktrace:
 [1] PFM(set::Vector{DNA})
   @ BioSequences C:\Users\Planck\.julia\packages\BioSequences\bYmYY\src\search\pwm.jl:50
 [2] PFM(set::LongSequence{DNAAlphabet{4}})
   @ BioSequences C:\Users\Planck\.julia\packages\BioSequences\bYmYY\src\search\pwm.jl:42
 [3] top-level scope
   @ In[22]:2

```

Now if I do:

```
dna1 = dna"TCA"
pfm = PFM([dna1])
```
```
4×3 PFM{DNA, Int64}:
 A  0  0  1 
 C  0  1  0 
 G  0  0  0 
 T  1  0  0 
```

Is there any reason?
thanks

**Comment by jakobnissen** [comment]
Dear @felipe-mansoldo 

PFMs and PWMs represent nucleotide frequencies at each position. E.g. if 7 out of 11 frequencies has a `DNA_C` at first position, its frequency is `7 / 11`. Hence, they need a collection of symbols to construct.

**Comment by felipe-mansoldo** [comment]
Dear @jakobnissen,
thanks for the explanation
my best
