### ISSUE TITLE
Faster computation of Kmer composition

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/BioSequences.jl#46]
Kmer composition is relatively widely used. The reason for using kmers rather than arbitrary length sequences are almost often the superior speed of kmers, hence it's an area worth optimizing.

Currently in BioSequences, calculating the kmer composition of a sequence relies on iterate(x::EachKmerIterator). However, rather than relying on a kmer iterator, counting kmers by a direct loop over each nucleotide of the sequence is significantly faster for longer sequences. In a test implementation I made, the kmer composition can be counted ~4x faster for long sequences (10k nt) using a direct loop, compared to the current BioSequences implementation.

I suggest changing the implementation of the method
`composition(iter::EachKmerIterator{T}) where {T<:Kmer}`
Such that it's calculated by direct iteration.

#### Advantages
- Quicker computation

#### Disadvantages
- Does not rely on the existing implementation of BioSequences.EachKmerIterator. This means that if the underlying structure of sequences change, updating BioSequences.EachKmerIterator will not be sufficient to making these methods work.

I have created an implementation of my proposed change at:
https://github.com/jakobnissen/biobag/blob/master/kmercount_newimpl.jl

__Note!__: I have not extensively tested my implementation for all the corner cases - I can write the test code if this proposal is accepted.

**Comment by BenJWard** [comment]
Hey @jakobnissen, Have you identified why the iterators are not faster than the direct loop? Is it something that can be fixed about the iterators or do you think there's a general issue with iterators being slower than direct loops?

**Comment by jakobnissen** [comment]
I don't know exactly what makes the iterator slower. Some weeks ago, I implemented my own biological symbols, biological sequences and Kmer library from scratch. Even though my implementation of both the biological sequence and my KmerIterator object differed from that in BioSymbols and BioSequences, I saw the same ~3x performance difference.
On the other hand the direct loop also uses `for i in 1:n`, which itself implements `iterate`, so I'm not sure it's something intrinsic with the iteration protocol.

**Comment by BenJWard** [comment]
This is surprising as the iterate method on BioSequences tries to do some things which are reasonably smart:

```
function Base.iterate(
        it::EachKmerIterator{T},
        state::Tuple{Int, UInt64}) where {T}

    k = kmersize(T)
    pos, kmer = state
    isok = true

    # faster path: return the next overlapping kmer if possible
    if it.step < k && pos + k - 1 ≤ lastindex(it.seq) && pos != it.start
        offset = k - it.step
        if it.step == 1
            nt = inbounds_getindex(it.seq, pos+offset)
            kmer = kmer << 2 | trailing_zeros(nt)
            isok &= iscertain(nt)
        else
            for i in 1:it.step
                nt = inbounds_getindex(it.seq, pos+i-1+offset)
                kmer = kmer << 2 | trailing_zeros(nt)
                isok &= iscertain(nt)
            end
        end
        if isok
            return (pos, T(kmer)), (pos+it.step, kmer)
        end
    end

    while pos + k - 1 ≤ lastindex(it.seq)
        kmer, ok = extract_kmer_impl(it.seq, pos, k)
        if ok
            return (pos, T(kmer)), (pos+it.step, kmer)
        end
        pos += it.step
    end

    return nothing
end
```

Such as reducing the amount of work to be done in the case where kmers overlap. I like your use of the kmerof lookup table. My instinct here is perhaps there is some synthesis here of the BioSequence code, and your script that will make any application (not just composition) that iterates over kmers more efficient.

**Comment by jakobnissen** [comment]
I think it's worth running a benchmark of the code in my script (pay especial attention to the case of >10k nucleotides, and step = 1 or step = 25). The use of lookup tables instead of `trailing_zeros` does give a 20%-ish performance boost (and similarly adding values to a dict using `value = get!(collection, key, 0); collection[key] = value + 1` is a little faster), but not enough to explain the large difference in time spent.

The direct loop is, of course, less elegant than relying on `iterate`, which is a more flexible solution.

**Comment by BenJWard** [comment]
I agree that iterate is a more flexible solution. I think we could do a PR on this issue in several stages, one stage might be to identify the performance gotchas you found with trailing_zeros and setindex apply fixes and observe the performance changes, then the next step is likey to sort out why on earth the current iterators are slower. It may well be that your method of generating the kmers from the sequence in the first place is a more efficient one, or involves less operations, or code branches less or is otherwise optimized better by the compiler. Or any number of things. As it goes this might pin down what exactly is currently the issue with BioSequences. Hopefully the iterate will just get better, but if not we could use your looping method, with some sauce that makes it tolerate changes to internal sequence representation. I've been doing quite a bit of work on refactoring the "bit-flipping" internals of BioSequences on my personal fork recently to make such internals easier to comprehend and to tolerate any future representation changes (although I don't anticipate any).

**Comment by jakobnissen** [comment]
That sounds like a good plan. I will fork BioSequences, implement the smaller changes, and make a PR. Then I'll look at the iterate and whether that can be optimized. To be continued!

**Comment by jakobnissen** [comment]
Right, so I've done a little digging. While doing so, several things came up, some of which I'll put in some other PRs not related to this subject.
I've written a page about what I've found:

https://github.com/jakobnissen/biobag/blob/master/kmerspeed.html
 
There are some small, simple fixes to the current implementation of `iterate`, but these will only give a ~25% speed increase. I think it's possible to get `iterate` to be really fast (which is great, because I've come to believe implementing the loop-based functions I originally proposed is a bad idea), but for that, some more kmer iterator types will need to be added, which will restructure the code of `eachkmer.jl`. For further speed, I believe it would be a good idea to write an explicit iterator of DNA bases.

Let me know what you think.

**Comment by BenJWard** [comment]
This is some really nice work @jakobnissen! I am very much pro all of your suggestions.

I'm currently doing work on BioSequences to include an "ShortSequence" abstract type, Kmers were to be a subtype, but also Codons, which I'm planning to add. 
In my group we've been doing work with "Skipmers" - see the readme here: https://github.com/bioinfologics/skm-tools. which are a generalisation of the kmer concept. A sequence of kmers is a sequence of skipmers with parameters n=1, m=1 and k. So a type `Skipmer{N,M,K}` is to make it's way to BioSequences, with an alias of `const Kmer{DNA,K} = Skipmer{1, 1, K}` (or something like that). Method specialisation is to be important here as well so I think this proposal is really very good. I'm also very much pro the idea of a more efficient sequence iterate method that doesen't repeately extract chunks too.

**Comment by jakobnissen** [comment]
For your information and for anyone potentially reading this issue down the road, I have attempted to create a more efficient iterator of nucleotides from a BioSequence as mentioned above, but got absolutely nowhere. The current implementation is very very fast (we're talking sub-nanosecond per nucleotide, apparently compiling down to just a few simple instructions), and while I managed to shave a few percent time off iteration, I think the added code complexity is not worth a few percent increase in speed.
