### ISSUE TITLE
map(f, seq) raises an exception

### ISSUE THREAD

**Issue by tanhevg** [BioJulia/BioSequences.jl#58]
Consider the following snippet:
```julia
using BioSequences
my_dict = Dict{AminoAcid, Float64}(...)
x = map(aa -> my_dict[aa], aa"PLEASANTLY")
```

## Expected Behavior
I would expect `x` to contain an array of `Float64`, taken from `my_dict`.

## Current Behavior
I get the following error (-3.5 is one of the entries in `my_dict`):
```
ERROR: InexactError: UInt8(UInt8, -3.5)
Stacktrace:
 [1] Type at ./float.jl:679 [inlined]
 [2] convert at ./number.jl:7 [inlined]
 [3] convert at /bmm/home/et517/.julia/packages/BioSymbols/8RyRT/src/aminoacid.jl:24 [inlined]
 [4] enc64(::BioSequence{AminoAcidAlphabet}, ::Float64) at /bmm/home/et517/.julia/packages/BioSequences/7i86L/src/bioseq/bioseq.jl:107
 [5] unsafe_setindex! at /bmm/home/et517/.julia/packages/BioSequences/7i86L/src/bioseq/indexing.jl:143 [inlined]
 [6] map!(::getfield(Ampliphyre, Symbol("##39#40")), ::BioSequence{AminoAcidAlphabet}) at /bmm/home/et517/.julia/packages/BioSequences/7i86L/src/bioseq/transformations.jl:172
 [7] map at /bmm/home/et517/.julia/packages/BioSequences/7i86L/src/bioseq/transformations.jl:178 [inlined]
```
## Possible Solution / Implementation
It appears that the method `function Base.map(f::Function, seq::BioSequence)` around `transformations.jl:177` is just wrong and should be removed.

## Your Environment
```
BioSequences v1.1.0
Julia Version 1.0.3
Platform Info:
  OS: Linux (x86_64-conda_cos6-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)
```

**Comment by BenJWard** [comment]
I'm not sure how the stdlib map behaves, but the docstring defines map and map! as:

```
map(f, c...) -> collection

  Transform collection c by applying f to each element. For multiple collection arguments, apply f
  elementwise.
```

So your function should be one that transforms each element of an amino acid sequence. And you can replace an amino acid in a sequence with a float64.

The examples of map given in the docs of the stdlib, also show that no changing of element type occurs:

```
Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> map(x -> x * 2, [1, 2, 3])
  3-element Array{Int64,1}:
   2
   4
   6
  
  julia> map(+, [1, 2, 3], [10, 20, 30])
  3-element Array{Int64,1}:
   11
   22
   33

``` 

In each case the arrays are always of Int64. BioSequences' version of `map` seems consistent with base julia and the stdlib in this regard, unless `map` has changed.

If you want to apply a function to each element of an amino acid sequence, and get a vector of floats as output, you can do that with an array comprehension, or a generator wrapped in a `collect`:

```julia
using BioSequences
my_dict = Dict{AminoAcid, Float64}(...)
x = [aa -> my_dict[aa], aa"PLEASANTLY"]
```

**Comment by BenJWard** [comment]
It turns out that the code for `map` in Base is actually `map(f, iters...) = collect(Generator(f, iters...))`, which was my second suggestion. This method does let the element type change, as it can be predicted from f through the generator through to collect which will construct the appropriate array with the right eltype.

BioSequences version of map is more strict in keeping to the text description in the docs of map. 

But perhaps we can define a similar map, that returns an Amino Acid Seqence is the eltype of f is AminoAcid, but if you use map as you do, then it will give you an array of some element.

This should be easy to do without causing type uncertainty.

**Comment by BenJWard** [comment]
On the other hand, stdlib map always returns vectors, no matter the input collection types, so it's probably not needed.

**Comment by kescobo** [comment]
@BenJWard Probably also add an `@deprecate` to the next minor version as well? Or if we're not yet at that stage of stability, that's cool (I've never used the deprecate macro).

**Comment by BenJWard** [comment]
This is resolved as far as I can see.
