### ISSUE TITLE
How to get the phred score in a string variable most efficiently?

### ISSUE THREAD

**Issue by dnk8n** [BioJulia/BioSequences.jl#59]
In a section of code I am writing, I want to read fastq file without making use of phred score at all. I would like to just have a string variable which would contain the phred line exactly as it is currently in the input fastq files.

New to Julia, so I have failed to work out how to do it. You must do it somewhere because `println(record)` (please see context below) results in the representation I am looking for.

```
fastq_stream = FASTQ.Reader(open("pool1.fastq", "r"))
for record in fastq_stream
    #pseudo-code from here
    # to_csv(record.name, record.sequence, record.quality, record.sequence.length())
end
close(fastq_stream)
```

Along with the bit in pseudo-code, I am also storing which sample each sequence belongs to and the barcode match error (from a demultiplexing function we use). The idea is for users to then filter the contents of the csv with all this extra information according to their own needs in order to produce filtered fastq files (outside scope of this issue, but thought I would add it for context).

The native list of  INT8 I get from FASTQ.quality(record, :sanger) does not store well in a CSV. At this stage a string would be better. When it comes to writing fastq files, I can then convert from string to this list format if necessary.

Any help or alternate recommendations would be very much appreciated.

## Your Environment

- Package Version used: Not sure how to find the version
- Julia Version used: 0.6.4
- Operating System and version (desktop or mobile):
Ubuntu inside a Docker container
```
uname -a

Linux a5d0b3698610 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dnk8n** [comment]
I was initially asking about how a user of your library could just get this information (believing that it is already stored somewhere for quick access).

However, I found a workaround which suits my needs:

`join(Char(i) for i in Vector{Int8}(FASTQ.quality(record, :sanger)) .+ 33)`

I am unsure why an offset of 33 is required here but this line is producing text equal to the original fastq files.

Is there a more efficient way?

**Comment by BenJWard** [comment]
If you just want the quality string that is in the FASTQ record, as is, you can do this:

```julia
quality = String(record.data[record.quality[part]])
```

We probably should have some API function that lets you get the quality string - as is, the current functions get the numeric scores from the encoded string, which is why there are the encoding variables (:sanger) and the offset values.
