### ISSUE TITLE
getindex not defined for arrays

### ISSUE THREAD

**Issue by diegozea** [BioJulia/BioSequences.jl#61]
I was trying to create a sequence without some index and I've found that `getindex` using arrays isn't supported:

```julia
using BioSequences
seq = dna"CCTAGGAGG"
seq[[1,2,3,7,8,9]] # MethodError
seq[[true, true, true, false, false, false, true, true, true]] # MethodError
```

**Comment by BenJWard** [comment]
Thanks for pointing this out @diegozea, perhaps we can include this method in version 2.0.

**Comment by ardakdemir** [comment]
I have been going over the source code to get familiar and to add this functionality. I could not understand how the decode function call in indexing.jl properly decodes the given Int representation. I could not find a decode function in the source code.

```
@inline function inbounds_getindex(seq::BioSequence{A}, i::Integer) where {A}
    j = bitindex(seq, i)
    @inbounds return decode(A, (seq.data[index(j)] >> offset(j)) & mask(A))
end
```

**Comment by BenJWard** [comment]
@ardakdemir The definitions for `encode` and `decode` are found here https://github.com/BioJulia/BioSequences.jl/blob/e54ee6b7652e64647bb326fe321be206649aaf4a/src/alphabet.jl#L127. How encoding and decoding is done, depends on the alphabet parameter `A` of the `BioSequence{A}`, and so `A` is the first argument to the `decode` method, so as Julia's compiler can select the correct `decode` method at compile time.

**Comment by ardakdemir** [comment]
@BenJWard Thanks for the explanation. @diegozea I have added a trivial implementation of subsequencing functionality on the "subsequencing" branch. Maybe you can give it a try.

**Comment by jakobnissen** [comment]
This appears to be fixed on master, so closing it
