### ISSUE TITLE
FASTA.Reader doesn't recognize the correct alphabet with ambiguous sites

### ISSUE THREAD

**Issue by cecileane** [BioJulia/BioSequences.jl#64]
I have a data set of DNA sequences, where some sites are ambiguous. In the example file below, the second sequence has `Y`, which means either `C` or `T`.
```
>P1
ATT
>P2
AYC
>P3
ATT
>P4
ATT
```

When I read this file with `FASTA.Reader`, the second sequence is thought to be an alignment of amino acids, because `Y` also means Tyrosine if we think about amino acids instead of nucleic acids:
```julia
julia> r = BioSequences.FASTA.Reader(open("myfile.fasta"))
julia> for record in r
         @show eltype(sequence(record))
       end
eltype(sequence(record)) = DNA
eltype(sequence(record)) = AminoAcid
eltype(sequence(record)) = DNA
eltype(sequence(record)) = DNA
```
I would like to tell `FASTA.Reader` that the `Y` character stands for `DNA_Y`, not `AA_Y`. Is there a way to tell the function that all the 4 sequences are DNA sequences?

```julia
(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [7e6ae17a] BioSequences v1.1.0
  [3c28c6f8] BioSymbols v3.1.0
  [336ed68f] CSV v0.5.5
  ...
```

**Comment by kescobo** [comment]
Not sure this is quite a bug, but it seems like one should be able to pass the type of sequence to `FASTA.reader` to override the inference. In the meantime, this isn't the most efficient, but it seems to work:

```julia
for record in r
    @show eltype(DNASequence(convert(String, sequence(record))))
end
```

**Comment by kescobo** [comment]
And you could do `if eltype(sequence(record)) <: AminoAcid` so you're only doing the conversion when you need to.

**Comment by cecileane** [comment]
fantastic, thanks!

**Comment by BenJWard** [comment]
You can pass the type of sequence to the `sequence(record)` method, e.g. `sequence(BioSequence{DNAAlphabet{2}}, record)` in the case where you know you have no ambiguous letters and want to force the minimum number of bits per symbol.

**Comment by BenJWard** [comment]
This behaviour is because, without a type to the `sequence`  method, some inference gets done at runtime to determine the sequence type. Which isn't optimal performance-wise anyway.

**Comment by cecileane** [comment]
My issue is because there *are* ambiguous letters. Otherwise, the sequence type is inferred as expected.

**Comment by BenJWard** [comment]
In that case `sequence(DNASequence, record)` (or `sequence(BioSequence{DNAAlphabet{4}}, record)` without using the alias), should do what you want. This uses the 4-bits per symbol encoding and includes the ambiguous letters.

**Comment by kescobo** [comment]
Oh, that's much nicer. I didn't realize that the sequence type remained unselected until the call to `sequnce`, that's a nice API, though a bit unexpected coming from eg biopython

**Comment by BenJWard** [comment]
@cecileane, does providing the type for the `sequence` method solve the problem you were having?

**Comment by cecileane** [comment]
Yes, that works great for me, thanks a bunch!
