### ISSUE TITLE
Type for Paired-end Reads

### ISSUE THREAD

**Issue by ardakdemir** [BioJulia/BioSequences.jl#66]
For generating contigs we need to make use of paired-end reads. I think it would be convenient to have a a type Paired-end BioSequence or we can modify the current version of the BioSequence type to have gaps. 

@BenJWard, I would be really happy to hear your comment about this one.

**Comment by BenJWard** [comment]
`BioSequence{DNAAlphabet{2}}` does not allow gaps but `BioSequence{DNAAlphabet{4}}` does. Why do you want gaps for paired end reads?

I do have a plan for dealing with reads in a better manner - especially for assembly and mapping: I'm going to implement "read-datastores", which can be built using FASTQ files, and act as efficient binary datastores for read datasets - reusable for all BioJulia projects. When we have those, it might be cool to have some kind of type like `PairedReads`, or even just `Pair{DNASequence,DNASequence}`. After we have PE I'll look at getting us Long Reads (PacBio and Nanopore) and TaggedReads (10X) datastores. For paired reads I don't know if I would use gaps. I think I would just map the two reads from a pair to the graph individually, if everything (reads + graph) make sense, then we would expect the two reads to map nearby to each other in the graph, with a distance between them around the average insert size of the library that was prepared for sequencing.

**Comment by ardakdemir** [comment]
My initial plan was to embed the average insert size information to a paired-end read by putting gaps between the two reads. For now, I also represent paired-end reads as a tuple (sequence1,sequence2,expected insert size). I think the approach you describe is more clean than inserting gaps which would take unnecessary space.
