### ISSUE TITLE
In 2.0 docs, link on left menu bar for searching goes to index, not page for search methods

### ISSUE THREAD

**Issue by Zymergen-phaverty** [BioJulia/BioSequences.jl#75]
> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Package Version used:
- Julia Version used:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by kescobo** [comment]
related to #73 / #74 ?

**Comment by Zymergen-phaverty** [comment]
Oops, yes this is a duplicate. Closing
